apiVersion: apps/v1
kind: Deployment
metadata:
  name: image-text-extractor-api
  namespace: image-text-extractor-rag-ai
spec:
  replicas: 1
  selector:
    matchLabels:
      app: image-text-extractor-api
  template:
    metadata:
      labels:
        app: image-text-extractor-api
    spec:
      containers:
      - name: api
        image: vashisthavinod/image-text-extractor-api:v8
        imagePullPolicy: Always
        env:
          - name: WEAVIATE_HOST
            valueFrom:
              configMapKeyRef:
                name: rag-config
                key: WEAVIATE_HOST
          - name: WEAVIATE_HTTP_PORT
            valueFrom:
              configMapKeyRef:
                name: rag-config
                key: WEAVIATE_HTTP_PORT
          - name: WEAVIATE_GRPC_PORT
            valueFrom:
              configMapKeyRef:
                name: rag-config
                key: WEAVIATE_GRPC_PORT
        volumeMounts:
        - name: logs
          mountPath: /app/logs
      volumes:
      - name: logs
        emptyDir: {}