apiVersion: v1
kind: Service
metadata:
  name: imageTextExtractor-rag-api-service
  namespace: imageTextExtractor-rag-ai
spec:
  type: NodePort
  selector:
    app: imageTextExtractor-rag-api-service
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 30007