apiVersion: apps/v1
kind: Deployment
metadata:
  name: weaviate
  namespace: imageTextExtractor-rag-ai
spec:
  replicas: 1
  selector:
    matchLabels:
      app: weaviate
  template:
    metadata:
      labels:
        app: weaviate
    spec:
      containers:
      - name: weaviate
        image: cr.weaviate.io/semitechnologies/weaviate:1.27.0
        ports:
          - containerPort: 8080
          - containerPort: 50051
        env:
          - name: QUERY_DEFAULTS_LIMIT
            value: "25"
          - name: AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED
            value: "true"
          - name: DEFAULT_VECTORIZER_MODULE
            value: "none"
          - name: PERSISTENCE_DATA_PATH
            value: "/var/lib/weaviate"
        volumeMounts:
          - name: weaviate-data
            mountPath: /var/lib/weaviate

      volumes:
        - name: weaviate-data
          emptyDir: {}   # change to PVC in production