apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: image-text-extractor-rag-ai
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s

    scrape_configs:
      - job_name: 'prometheus'
        static_configs:
          - targets: ['localhost:9090']

      - job_name: 'image-text-extractor-api'
        metrics_path: /metrics
        static_configs:
          - targets: ['image-text-extractor-api:8000']