apiVersion: v1
kind: Service
metadata:
  name: jaeger
  namespace: image-text-extractor-rag-ai
spec:
  selector:
    app: jaeger
  ports:
    - name: ui
      port: 16686
      targetPort: 16686
    - name: grpc
      port: 4317
      targetPort: 4317
    - name: http
      port: 4318
      targetPort: 4318