apiVersion: v1
kind: ConfigMap
metadata:
  name: rag-config
  namespace: image-text-extractor-rag-ai
data:
  WEAVIATE_HOST: "weaviate.image-text-extractor-rag-ai.svc.cluster.local"
  WEAVIATE_PORT: "8080"
  WEAVIATE_HTTP_PORT: "8080"      # <--- ADD THIS LINE
  WEAVIATE_GRPC_HOST: "weaviate.image-text-extractor-rag-ai.svc.cluster.local"
  WEAVIATE_GRPC_PORT: "50051"
  LOG_DIR: "/app/logs"

  OTEL_EXPORTER_OTLP_ENDPOINT: "http://jaeger:4317"
  OTEL_SERVICE_NAME: "image-text-extractor-rag-agent"