name: Scan Docker Image

on:
  workflow_run:
    workflows: ["Build and Push to ECR"]
    types:
      - completed

jobs:

  scan:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
    - name: Scan Image with Trivy
      uses: aquasecurity/trivy-action@master
      with:
#        image-ref: ai-platform:${{ github.event.workflow_run.head_sha }}
         image-ref: 632804446443.dkr.ecr.us-east-1.amazonaws.com/ai-platform:${{ github.event.workflow_run.head_sha }}