name: Run Tests

on:
  push:
    branches:
      - main

jobs:
  test:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install Dependencies
      run: pip install -r ai-platform/docker/requirements.txt

    - name: Install pytest
      run: pip install pytest

    - name: Run tests
      run: pytest